### ISSUE TITLE
Build every commit on Appveyor

### ISSUE THREAD

**Issue by szepeviktor** [FauxFaux/PuTTYTray#284]
This is almost done
https://ci.appveyor.com/project/szepeviktor/puttytray/build/1.0.18

@FauxFaux Could someone help me finish it?

```yaml
version: 1.0.{build}
image: Visual Studio 2015
install:
- cmd: >-
    mkdir doc
    perl licence.pl
    cd charset & perl sbcsgen.pl & cd ..
    C:\Python35\python mkcmake.py > CMakeLists.txt
    cmake .
    cd windows
    build-debug
build: &1826105770 off
test: off
```

**Comment by szepeviktor** [comment]
Progress :)

https://ci.appveyor.com/project/szepeviktor/puttytray/build/1.0.22

```yaml
version: 1.0.{build}
image: Visual Studio 2015
environment:
  PYTHON_VERSION: 3.5
install:
- &710229540 cmd: >-
    mkdir doc

    perl licence.pl

    cd charset & perl sbcsgen.pl & cd ..

    C:\Python35\python mkcmake.py > CMakeLists.txt

    cmake .
before_build:
- cmd: dir
build:
  project: putty.sln
  verbosity: normal
test: off
```
